version: '3.7'

services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
    volumes:
      - ./addons:/mnt/extra-addons  # папка для твоих кастомных модулей
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - odoo-web-data:/var/lib/odoo
    restart: always

volumes:
  odoo-db-data:
  odoo-web-data: